#!/usr/bin/env bash
# configure Nginx to listen on port 80 for all active IPv4 IPs
cat /etc/nginx/sites-available/default >  /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
